# Generated by Django 3.2.5 on 2021-07-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('profile_picture', models.ImageField(upload_to='profile_images/', verbose_name='Profile picture')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone number')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room number')),
                ('_subjects', models.ManyToManyField(db_column='subjects', to='directory.Subject')),
            ],
        ),
    ]
